### ISSUE TITLE
文件上传 文件夹 与 数据库

### ISSUE THREAD

**Issue by GuXiangFly** [panhainan/foblog#1]
请问 为何不将文件上传的文件夹为何不在 github上加上呢？ 为何数据库没有t_recommend 这个表？

**Comment by panhainan** [comment]
文件上传的文件夹是因为idea自动将没有内容的空文件夹给去掉了，这个在服务器运行后会自动生成的；如果需要它显示，那么可以在文件夹里面加个占位符（一个简易文件啥的）。
数据库刚刚看了一下是因为sql文件没有及时更新。
现已修好。感谢！
