### ISSUE TITLE
你好，能咨询一下你的服务器怎么弄得嘛

### ISSUE THREAD

**Issue by ruqinhu** [panhainan/foblog#3]
我准备参考你的代码也搭一个个人网站，就是不知道怎么弄到服务器上的，能把流程发一下嘛

**Comment by panhainan** [comment]
抱歉，在备战考研，没什么时间呢，你看到我说明文档都没有写完呢。弄服务器其实蛮简单的，你Google一下，和你在本地部署差不了太多，当然你可以做做缓存啊，什么的就会复杂些

**Comment by ruqinhu** [comment]
好吧，我试试，祝你考研成功

**Comment by ruqinhu** [comment]
你好，测试的时候运行过测试方法了。进入登陆界面，登入不了啊，点击登陆按钮没反应。能借我你网站的登陆密码我测试下吗？诚心。

**Comment by ruqinhu** [comment]
兄弟，你的managecontroller是不是没上传啊
